SELECT * FROM DARBUOTOJAI
SELECT GIMIMO_DATA FROM DARBUOTOJAI
SELECT VARDAS, PAVARDĖ, PAREIGOS FROM DARBUOTOJAI
SELECT DISTINCT SKYRIUS_PAVADINIMAS FROM DARBUOTOJAI
SELECT * FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos"
SELECT PAREIGOS FROM DARBUOTOJAI WHERE VARDAS = "Giedrius"
SELECT * FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1986-09-19"
SELECT VARDAS FROM DARBUOTOJAI WHERE PAVARDĖ = "Sabutis"
SELECT VARDAS, PAVARDĖ FROM DARBUOTOJAI WHERE PAREIGOS = "Programuotojas" AND SKYRIUS_PAVADINIMAS = "Gamybos"
INSERT INTO DARBUOTOJAI VALUES ("Jaunius", "Šindeikis", "1988-03-12", "Komandos vadovas", "Gamybos")
INSERT INTO DARBUOTOJAI (VARDAS, PAVARDĖ, GIMIMO_DATA) VALUES ("Rimantas", "Kundrotas", "1987-11-12")
UPDATE DARBUOTOJAI SET PAREIGOS = "Programuotojas", SKYRIUS_PAVADINIMAS = "Gamybos" WHERE VARDAS = "Rimantas" AND PAVARDĖ = "Kundrotas"
DELETE FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1987-11-12"
INSERT INTO DARBUOTOJAI VALUES ("Jonas", "Antanaitis", "2000-12-12", "Programuotojas", "Gamybos"); INSERT INTO DARBUOTOJAI VALUES ("Petras", "Antanaitis", "2000-12-12", "Programuotojas", "Gamybos")
UPDATE DARBUOTOJAI SET PAREIGOS = "Testuotojas" WHERE PAVARDĖ = "Antanaitis"
SELECT count(*) from DARBUOTOJAI WHERE PAREIGOS = "Testuotojas"
